dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=now-cli
    - RUST_BACKTRACE=1

matrix:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: nightly

before_install:
  - set -e

install:
  - sh scripts/install.sh
  - source ~/.cargo/env || true

script:
  - bash scripts/script.sh

after_script: set +e

before_deploy:
  - sh scripts/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  api_key:
    secure: "jKu1JeKjsiaIY6U6L4SBALrnRSw5/57OR0esNDM8ISyAhJ0lXpJxzZqELFwn1idsFbbInGFog94QmDRBRK88R0wUxuktFKAsIxmts1tnCNPHzJGzngct79LFPBtifMgrIAjmo+1poTuSyAkPcEq4Nz82rPTUq8FB5U6Xco9+1rbKc6OZycKm4XU5jRQBlmOOuezGtdzR3pW61WvZX9fsRq50CEa4X4izwD5wy4wvSY+hRDFKC1Zdl7bjM10I8dvqpMJBEvhBEZnBUQj0O1U8xh/CpL5wYC8qqAR9xk4YNNQvM34KFFW4/Wcm+Ir12K8lItm/3mXpyLyR+ydIMUihx6adCeilDb+Q/l/GrhWLkHtnzonaRiSU4DS5Htws/lZpPCLkYoy8cqyZJhdaGbB+iMN5Lsixe0/A2+V+wgp5r4R2DuDDzdsfWQKMuF0jqM4U50Z2sLjrSzncdLWNEIsDdlxNbt/eaVCzv7SF8vW1FZoKjiIpZnCz6/mWLAla7AsAINxonmzwuTlZD/J3mjRBTekDXfwFFN3kQPKsTYBye1JgpDlbJxg5a0o+IROME1ybMGz9GXS0DDHJdaZcWa0X/iQgJ1thPnwgmIPOTqUD03zUyOWvWVkWcTg4RNhveL9stTsaN78UR1nnYwptwm+C+h4RvG++01uPmG1c8X1RTU8="
  on:
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
    on_failure: never
